name: enhanced_future_builder
description: Wrapper that improves readability and solves the common refiring FutureBuilder problem
version: 1.0.3
homepage: https://github.com/sleeyax/enhanced_future_builder
author: Sleeyax <yourd3veloper@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0
  test: ^1.6.0

dependencies:
  flutter:
    sdk: flutter
